server:
  port: 8888

spring:
  profiles:
    active: native    # <--- заставит Config Server работать в native режиме
  cloud:
    config:
      server:
        native:
          # путь к "репо" с конфигами (относительно рабочего каталога приложения)
          search-locations: file:./config-repo
